db:
  host: ${AUTH_SERVICE_DB_HOST}
  port: ${AUTH_SERVICE_DB_PORT}
  database: ${AUTH_SERVICE_DB_NAME}
  user: ${AUTH_SERVICE_DB_USER}
  password: ${AUTH_SERVICE_DB_PASSWORD}
spring:
  webflux:
    base-path: /auth-api
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}
    user: ${db.user}
    password: ${db.password}
jwt:
  expirationInMinutes: 5
  secret: ${AUTH_SERVICE_JWT_SECRET}
password:
  max-length: 15
  min-length: 8
  min-upper-case: 1
  min-lower-case: 1
  min-digit: 1
  min-special: 1

springdoc:
  default-produces-media-type: application/json
server:
  host: localhost
  protocol: http