db:
  host: ${AUTH_SERVICE_DB_HOST}
  port: ${AUTH_SERVICE_DB_PORT}
  database: ${AUTH_SERVICE_DB_NAME}
  user: ${AUTH_SERVICE_DB_USER}
  password: ${AUTH_SERVICE_DB_PASSWORD}
spring:
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    url: jdbc:postgresql://${db.host}:${db.port}/${db.database}
    user: ${db.user}
    password: ${db.password}
jwt:
  expirationInMinutes: 5
  secret: ${AUTH_SERVICE_JWT_SECRET}